# Generated by Django 4.0 on 2022-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='img',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
    ]
