# Generated by Django 4.0 on 2022-03-03 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0004_confession_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
