# Generated by Django 4.0 on 2022-03-03 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0005_alter_confession_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='id_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='confession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
