# Generated by Django 4.0 on 2022-03-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0006_confession_id_num_alter_confession_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='id_num',
        ),
    ]
