# Generated by Django 4.0 on 2022-03-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0007_remove_confession_id_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confession',
        ),
    ]
